#!/command/with-contenv sh
set -eu
# export env paths
set -a
. /etc/openwrt-builder/paths.env
set +a

export PYTHONPATH="/usr/lib/openwrt-builder:${PYTHONPATH}"
exec python3 -m openwrt_builder.main

printf "\033[32mINFO\033[0m OpenWRT ImageBuilder started\r"