#!/command/with-contenv sh
printf "\033[32mINFO\033[0m Starting OpenWRT ImageBuilder\n"

set -eu
# export env paths
set -a
. /etc/openwrt-builder/paths.env
set +a

env | while IFS='=' read -r k v; do
  case "$k" in
    OPENWRT_BUILDER_*_DIR)
      [ -n "$v" ] && mkdir -p -- "$v"
    ;;
  esac
done

export PYTHONPATH="/app/openwrt-builder:${PYTHONPATH:-}"
printf "\033[32mINFO\033[0m OpenWRT ImageBuilder API manager started\n"
exec python3 -m openwrt_builder.main
