#!/command/with-contenv sh
set -eu

# export env paths
set -a
. /etc/openwrt-builder/paths.env
set +a

# create dirs from env
env | while IFS='=' read -r k v; do
  case "$k" in
    OPENWRT_BUILDER_*_DIR) mkdir -p "$v" ;;
  esac
done

# copy examples
# mkdir -p "$EXAMPLES_DIR"
