#!/command/with-contenv sh
printf "INIT" >&2
set -eu

# export env paths
set -a
. /etc/openwrt-builder/paths.env
set +a

# create dirs from env
while IFS='=' read -r k v; do
  case "$k" in
    OPENWRT_BUILDER_*_DIR)
      [ -n "$v" ] || continue
      mkdir -p -- "$v"
    ;;
  esac
done <<EOF
$(env)
EOF

# copy examples
# mkdir -p "$EXAMPLES_DIR"
